### ISSUE TITLE
Choose device type

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#1]
First of all, this is a fantastic initiative! Thanks a lot

This is more of a query than a bug report. I'm confused 
I noticed that many apps say “varies with device”. Are these apps being ignored? If yes, could you implement a feature to choose device type?

**Comment by JusticeRage** [comment]
Hi, and thank you for your interest in ApkTrack!

The "Varies with device" message is directly taken from the Play Store page of an application. For instance, you can find it for [Google Maps](https://play.google.com/store/apps/details?id=com.google.android.apps.maps). When that happens though, ApkTrack tries to find the version number on the "changelog" section of [AppBrain](https://www.appbrain.com/app/google/com.google.android.apps.maps).

If your apps status remains on "varies with device", it means that no version could be obtained from AppBrain, even though the application exists on the Google Play Store. Do you have an example of such an app (application name or package name if you can) so I can look into it?

To answer more broadly, I sadly haven't found a way to identify as a specific device on the Play Store (is that even possible?).

**Comment by ghost** [comment]
Thanks for the explanation. Frankly I'm still getting trying to figure out everything. And the “not a play store app” entries make it a bit cluttered. I hope you implement a way to hide/sort them soon. 
Will let you know more as I find out
Thanks again
