### ISSUE TITLE
connection issue 

### ISSUE THREAD

**Issue by Incedis** [JusticeRage/ApkTrack#102]
I am getting the below error. 
Even though intermittent, it is reproducible quite a lot. 
Reboot the  client and the issue goes away for a little while but comes back very quickly. 
Same issue with or without VPN 
Switching providers does not help. 
02-17 12:59:25.429  9732 13380 V ApkTrack: Could not connect to the UpdateSource (timeout).
02-17 12:59:25.431 14487 14487 I Atfwd_Sendcmd: AtCmdFwd service not ready - Exhausted retry attempts - :6

[cat.txt](https://github.com/JusticeRage/ApkTrack/files/783130/cat.txt)

PS: Same issue on different network. I can go days without having any notification of new version even though I have checked 'automatically download APKs'

**Comment by JusticeRage** [comment]
Hi!
Based on my [research](https://code.google.com/p/android/issues/detail?id=226122) (this is the first time I've seen this error), this might be an issue caused by your device and not the app. Do you have a Nexus 6P?

**Comment by Incedis** [comment]
Yes Nexus 6P

**Comment by JusticeRage** [comment]
In that case, I'm afraid that this is a kernel issue that I can't do much about... Future updates may solve the problem. Sorry I can't be of more help!

**Comment by Incedis** [comment]
Ah AtCmdFwd service have it. Ok. Thanks
