### ISSUE TITLE
Better version comparison

### ISSUE THREAD

**Issue by JusticeRage** [JusticeRage/ApkTrack#11]
Presently, ApkTrack checks for version mismatches and not version updates.
It is a bit dumb in the sense that it checks for versions mismatches, not version increases. If web sources say the latest version is "1.0" and you have "2.0" installed, it will notify you that the application can be updated.
Detecting version number increases generically is actually a difficult problem because of the diversity. For instance, look at Google Music's version string: 5.8.1810R.1720607. It's a mix of numbers, letters, and points.

Run tests to figure out if alphabetical comparison is sufficient.

**Comment by JusticeRage** [comment]
On the top of my head, I would say that alphabetical order is not sufficient, because `1.0.9 > 1.0.10`.

**Comment by precla** [comment]
Maybe this can help (it's JS, but you should get the idea):
https://gist.github.com/TheDistantSea/8021359

**Comment by JusticeRage** [comment]
Thanks for the link! This'll definitely be useful!

**Comment by utack** [comment]
Would be nice to see this happening. It will probablly never work 100%, but something like 1.8.1>1.7.1 should fix almost all false positives.

**Comment by JusticeRage** [comment]
That's the next item in my ToDo list!
