### ISSUE TITLE
[Feature suggestion] Enable removing all downloaded APKs in ApkTrack

### ISSUE THREAD

**Issue by Olf0** [JusticeRage/ApkTrack#110]
Please enhance ApkTrack to provide the ability to remove all downloaded apks in <android_storage/Android/data/fr.kwiatkowski.ApkTrack/files/Download/>. 
Currently, they pile up there (at least when one decides not to install downloaded apks). 

Side note: I also think it would be better to overwrite existing apks in <android_storage/Android/data/fr.kwiatkowski.ApkTrack/files/Download/> (instead of numbering them -2, -3, ...).

Tested with ApkTrack 2.1.1 under AOSP 4.1.2

**Comment by JusticeRage** [comment]
This is something I've been thinking about, yeah.
As for overwriting apks, the downloads are operated by the ststem's `DownloadManager` so I'm not sure this is something I have control over.

**Comment by Olf0** [comment]
Thanks for considering such an option.  Well, it would be just convenient for me (now that I know where to find and eventually delete the downloaded apks), but for less experienced users many megabytes of apks just pile up there without any notice or ability to remove them easily. 

WRT overwriting existing downloads: I expected that there should be flag for this in Android's APIs, but that was just a guess.

**Comment by JusticeRage** [comment]
I've worked on this feature and created a [test APK](http://apktrack.kwiatkowski.fr/apk/ApkTrack_test.apk). Would you care to test it and let me know if it solves this issue?

**Comment by Olf0** [comment]
Thanks a lot, @JusticeRage: This current `ApkTrack_test.apk` resolves issue #110 (this one) and the "missing desktop icon issue" discussed in issue #111 for me. 
Cheers! 
Hopefully it also resolves #106, but as none of the APKs on your server have been affected, we will see, if the compiled APK on F-Droid behaves well, too.  Looking forward to that. :)

**Comment by Olf0** [comment]
Tested this new feature a bit more: Working well, thus closing this issue.
