### ISSUE TITLE
[Suggestion] Enhance ApkTrack's appearance and description on F-Droid

### ISSUE THREAD

**Issue by Olf0** [JusticeRage/ApkTrack#111]
ApkTrack's appearance and description could be easily enhanced, in order to make it more attractive: 

- Its description is currently somewhat misleading, as "Check for updates on PlayStore" may be interpreted that ApkTrack is only usable for PlayStore users (as Yalp Store is).  My suggestion is to enhance the description, clearly denoting that ApkTrack also queries other apk sources, e.g. as such: 
Check for updateable apps on F-Droid, PlayStore and other sources
Periodically checks, if updates for installed apps exist.
ApkTrack was created for users who don't use the Google PlayStore, but still want to know when new APKs are available for their apps. It performs simple website scraping to search for the latest versions of packages installed on the device. ApkTrack can query F-Droid, PlayStore, Xposed, plus many other sources of APKs via the ApkTrack Proxy. 

- ApkTrack's icon is [missing on f-droid](https://f-droid.org/packages/fr.kwiatkowski.ApkTrack/). 
Please upload an icon to f-droid (e.g. simply the existing desktop / "launcher" icon), as this currently looks quite ugly and a careless (like: not really maintained) in the f-droid client: 

![screenshot_20170902_001](https://user-images.githubusercontent.com/16547876/29992531-de330d2a-8f9d-11e7-97cd-934bdbe9f9bd.png)

![screenshot_20170902_002](https://user-images.githubusercontent.com/16547876/29992534-ec03d77c-8f9d-11e7-9e26-fe11385381bd.png)

**Comment by JusticeRage** [comment]
Sadly, I don't maintain the F-Droid branch... I have no say in how the application is described, or how it looks over there.

**Comment by Olf0** [comment]
> Sadly, I don't maintain the F-Droid branch... 

Oh, I was not aware that the F-Droidians are acting so independently of the original software authors. 

> I have no say in how the application is descqqribed, or how it looks over there. 

O.K., [I try to address this issue to them](https://gitlab.com/fdroid/fdroiddata/issues/861) (utilising this issue description here).

**Comment by mimi89999** [comment]
> I have no say in how the application is descqqribed, or how it looks over there.

@JusticeRage Of course you do. Just edit https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/fr.kwiatkowski.ApkTrack.txt and open a MR in that repo (https://gitlab.com/fdroid/fdroiddata).

For the icon, is it PNG? Only PNG icons are supported. Also, icons in other formats than PNG won't show in the launcher on older Android versions.

**Comment by JusticeRage** [comment]
@mimi89999 Thanks for letting me know! As I wasn't the one who added the project to F-Droid, I don't know much about how to interact with it.
As for the icon, it is indeed a Vector image. I think Android support libraries now offer support for older devices, but that would probably require code modifications in the F-Droid client.

**Comment by Bubu** [comment]
@JusticeRage I just tried ApkTrack on a KitKat(19) device. It only shows the green android icon.

![image](https://user-images.githubusercontent.com/105185/30347780-784d05e2-980d-11e7-8781-0e2399ffdfea.png)

Just double checked with the apk from apktrack's website.

**Comment by Bubu** [comment]
I adjusted the summary and description according to @Olf0's suggestions.
That leaves the icon problem. :-)

**Comment by Olf0** [comment]
> I just tried ApkTrack on a KitKat(19) device. It only shows the green android icon. 

Well, this is a different issue: "Missing desktop icon after installation", in contrast to "missing icon on F-Droid". 
I have also observed this happening consistently across multiple installations, upgrades and removals of ApkTrack versions from F-Droid and from @JusticeRage's server on my test phone (Jolla 1 with AOSP4.1.2 based Android runtime environment). 
But on my "production" phone, with the same software stack and almost the same installed applications and configuration, I do have a desktop icon installed (though I reinstalled ApkTrack only twice, there). 
Thus I hesitated to open *another* issue, as I felt this needs more testing.  Feel free to do so: I will comment there, if I have any new insights into this. 

But actually, (now) I would *rather* like to see the "gradle bug" (issue #106) fixed first, as it may bear some other side-effects (apart from "crashing when entering the settings), and start testing the "Missing desktop icon" issue more thoroughly thereafter.

**Comment by Bubu** [comment]
@Olf0 I think in this case it's the same issue. ApkTrack has a VectorDrawable Icon, which is only supported (natively) by SDK>=21. F-Droid also doesn't (yet) support those.

Apparently there should be a png icon generated during the build ([see here](https://stackoverflow.com/questions/40955207/how-to-generate-png-from-vector-drawable-launcher-icon-with-minsdkversion-21)) but his doesn't seem to happen here.

**Comment by Olf0** [comment]
[New issue: Missing desktop icon after ApkTrack's installation] 

Well, this is what it looks like on my production phone's desktop (inside the folder "App stores"): 
![screenshot_20170913_001](https://user-images.githubusercontent.com/16547876/30351433-a0876d00-981b-11e7-97a8-a8e733ddc171.png)
So it works sometimes / worked sometime! 

But on my test phone's desktop there is just a black void, where ApkTrack's desktop icon ought to be:
![screenshot_20170913_002](https://user-images.githubusercontent.com/16547876/30351715-1374f5ca-981d-11e7-97f7-4b5fb583cc57.png)

This is at API level 16 (in both cases, certainly).

It's a shame: ApkTrack's icon is really good looking and nicely depicting what ApkTrack does, but only a few can ever see it (on their device's desktop and no one on F-Droid).

**Comment by JusticeRage** [comment]
After doing some research, it seems that vector images are NOT acceptable as launcher icons in any circumstances. I will revert them to PNGs immediately which should solve this issue.

**Comment by Olf0** [comment]
The "missing desktop icon issue" is resolved in the current `ApkTrack_test.apk` (see issue #110)  
As far as I understand, the original issue here ("missing ApkTrack icon on F-Droid") should be automatically resolved, when a fixed version of ApkTrack is published by F-Droid.  I will be closing this issue, then.

**Comment by Olf0** [comment]
Thanks to @Bubu for updating [the crucial parts of the description text](https://gitlab.com/fdroid/fdroiddata/commit/5d68aad0df8e87b71b0a9cd68b0d7905575b15b0).

Thanks to @JusticeRage, this issue is finally and completely resolved (including the "missing icon" part) by the release of ApkTrack 2.1.2 on F-Droid, today.
