### ISSUE TITLE
Integration with http://apps.evozi.com/apk-downloader/

### ISSUE THREAD

**Issue by BoBeR182** [JusticeRage/ApkTrack#12]
http://apps.evozi.com/apk-downloader/ lets you download google play apps without a google account. This plus your app could become an opensource google play store.

**Comment by JusticeRage** [comment]
I know about this service, however I'm not sure Evozi would be very happy with us automatically grabbing APKs from their website. The service costs them money.
I have also found that their APKs were sometimes outdated, even when a redownload is forced.

I'll get in touch with them to see if we can find an arrangement, but not before ApkTrack has gained some maturity and traction.

**Comment by ghost** [comment]
I doubt they'd allow it. There are so many ads on the website.

**Comment by BoBeR182** [comment]
Intergrate as part of issue #7 then?

**Comment by ghost** [comment]
Yes that would be a better option

**Comment by JusticeRage** [comment]
I'll add a note on #7 and close this one then.

**Comment by xDragonZ** [comment]
We can provide you direct API access to check the version. You are not allowed to query the APK as it will try fetch the APK file which will cause unnecessary load.

**Comment by JusticeRage** [comment]
Hi! Thank you for getting in touch with me, I would love API access!
I would like to clarify that I'm not using your website to get the APK's version. If I detect that an update is available (through other means), I offer the option to open the browser on an URL like this one (http://apps.evozi.com/apk-downloader/?id=com.touchtype.swiftkey), which to my knowledge doesn't trigger an APK fetch without user action.
