### ISSUE TITLE
New Logo Proposal for ApkTrack

### ISSUE THREAD

**Issue by mdnazmulhasan27771** [JusticeRage/ApkTrack#132]
Hello,
This my logo/Icon design for your project. It's free.I design this logo using adobe illustrator cc 2017. I hope you like this logo

![apktrack-01](https://user-images.githubusercontent.com/35112507/38464822-87683e9a-3b35-11e8-8bcf-707d7379c48f.jpg)

If you need anything change please contact me

Md Nazmul Hasan
Email : mdnazmul.hasan27771@gmail.com

Thank You.

**Comment by JusticeRage** [comment]
Hi! Thanks a lot for this icon!
Unfortunately, I think I like the previous one better; this one doesn't really capture the idea of what ApkTrack's doing.
