### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by abdulmalikkhan655** [JusticeRage/ApkTrack#133]
Hello, @JusticeRageI want to contribute in "ApkTrack" so i  want to designed a new logo for "ApkTrack" and it's free.

I hope you like it. If you like it, I will send you pull request, editable files/original source and .png format files. If there's something you want to change, I'll do it.
if you want i will send you my design

contact me on facebook for fast delivary 
[facebook profile redacted]

**Comment by JusticeRage** [comment]
Hi! I can't see any logo proposal in this issue.

**Comment by abdulmalikkhan655** [comment]
ok sir thanks for reply
