### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ashutosh-Kukreti** [JusticeRage/ApkTrack#134]
It is showing updates for apps like twilight and xender.
Also it is still scanning for updates for system apps even after ignoring system apps in the settings.
Can you please add one more source so that it can scan for updates of apps like GBwhatsapp?

**Comment by Ashutosh-Kukreti** [comment]
The apps twilight and xender are already up to date.

**Comment by JusticeRage** [comment]
Hi! For the issue regarding apps reported outdated while they're not, you're not giving me enough information to go on. I would suggest looking at #97 to make sure this is not expected behavior.

I don't know what GBwhatsapp is. None of the current sources support it? What new source would you suggest?

**Comment by Ashutosh-Kukreti** [comment]
Hi I looked at the issue and i think this is something else.
Well there is no perfect source.
The latest version is 8.3 according to playstore.
![screenshot_20180830-171437](https://user-images.githubusercontent.com/38154154/44850061-aee40700-ac79-11e8-87e6-e57d9bd97ab6.png)
![screenshot_20180830-171515](https://user-images.githubusercontent.com/38154154/44850062-b1466100-ac79-11e8-8430-1db44fa8b3c0.png)

**Comment by Ashutosh-Kukreti** [comment]
Maybe it is happening because of regional differences.Please check the version on your playstore app.

**Comment by JusticeRage** [comment]
All I can say is that the 9.0 version is available [here](https://www.apkmirror.com/apk/urbandroid-team/twilight/twilight-9-0-release/). If you'd rather stick to Play Store versions, feel free to switch to that update source by long-pressing on the app in the list.

**Comment by Ashutosh-Kukreti** [comment]
Okay, Thanks :)
You can use this source for all the GB apps it is the official site:
http://www.gbmods.co/

**Comment by Ashutosh-Kukreti** [comment]
After choosing playstore it says can not read version information.
Also can you add refresh app list option at the top , so that i can access it by clicking on 3 dots on the top right corner.

**Comment by JusticeRage** [comment]
GB apps: I can't read persian, sorry...
Play Store cannot read version information: you'll need to check the logcat of your device to get more information about what is going on.
Refresh app list button: It's on top of the screen for me. You probably need a device that has a bigger screen, as buttons are collapsed automatically when there is no space.
