### ISSUE TITLE
Xposed optional

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#15]
Please make Xposed modules optional? The Xposed installer is decent enough to check for updates.

**Comment by JusticeRage** [comment]
Is it really a problem to have ApkTrack check for them too?
In any case, this should happen naturally when #4 is fixed.

**Comment by ghost** [comment]
It is quite distracting to be honest. I have lots of modules installed and as I said, Xposed installer does a fantastic job already to look for updates and download as well. So it does feel a bit redundant on ApkTrack. I'm strictly using this for Play store updates.

**Comment by JusticeRage** [comment]
I'll look into it, but ApkTrack has no way to know if an application is an Xposed module before checking updates for it (i.e. before it finds out that the apps only exist in the Xposed repository).

Would you want to hide the Xposed modules from the application list? Is it okay if you don't see them, but still get notifications in the tray when new updates are available?

**Comment by ghost** [comment]
All Xposed modules have a metadata called “xposedmodule” in the manifest. Shouldn't that be enough to filter before checking for updates?

**Comment by JusticeRage** [comment]
I'm going to look into this again. The metadata will be useful to detect that the Xposed update source should be set automatically. I'll also add an option to ignore all Xposed apps in the settings.
