### ISSUE TITLE
Put ApkTrack on the Play Store

### ISSUE THREAD

**Issue by JusticeRage** [JusticeRage/ApkTrack#21]
Some users have requested ApkTrack to be released on Google's Play Store.
While this looks like it kinda defeats the point to me, it seems that there are some use cases where this could be useful (ex: when the Play Store app is put into hibernation).

The Play Store registration costs $25 though, and I'd rather not be paying to release free software. If I reach 25$ in donations, I'll put ApkTrack on the Play Store.
Current money received: $2,50.

**Comment by javiersantos** [comment]
I'm sorry to tell you this, but you won't be able to publish the app on Google Play. According to the [Content Policies](https://play.google.com/about/developer-content-policy.html):
- **Dangerous Products**: We don't allow content that harms, interferes with the operation of, or accesses in an unauthorised manner, networks, servers, application programming interfaces (APIs) or other infrastructure.
  - An app downloaded from Google Play may not modify, replace or update its own APK binary code using any method other than Google Play's update mechanism.

[Beta Updater for WhatsApp](https://github.com/javiersantos/WhatsAppBetaUpdater.Android) was pulled out from the Play Store by this reason.

**Comment by JusticeRage** [comment]
Ah, well that settles that. Thanks for pointing this out.
Although some users had requested this, I had never been a big fan of distributing the app through the Play Store when it was designed especially not to use it. I'll close the issue!
