### ISSUE TITLE
Missing resource

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#22]
The last tagged version is giving me resource erros, see https://f-droid.org/wiki/page/fr.kwiatkowski.ApkTrack/lastbuild_3 .

**Comment by JusticeRage** [comment]
Thank you for reporting this. All the errors should be fixed, and I have updated the 1.0b tag to the compiling release.
On a side note, is there a way I could sign the F-Droid releases with my own keys?

**Comment by ghost** [comment]
Thanks for the quick response. About the signing keys: We have a technical solution that compares two binaries, one build by fdroid and one provided by upstream, and if they match, we publish the one signed by upstream. This is a bit rough around the edges and requires also work on your side (standardizing on a build environment etc..), but might be a possibillity. You should talk to @eighthave about this -- his mail is on the github user page.
