### ISSUE TITLE
Add option for custom repositories

### ISSUE THREAD

**Issue by Mosrite** [JusticeRage/ApkTrack#30]
Maybe you could add an option to add custom repositories? Some apps or developers offer their own repositories, such as the Guardian project for example (https://guardianproject.info/repo/). People can add these repos to f-droid, but they aren't part of the official f-droid repo, so apktrack doesn't check them.

**Comment by JusticeRage** [comment]
I've toyed with the idea of letting the user type in his own repository, but I don't think this is going to work. Typing regular expressions on a smartphone keyboard is a total pain.
To add more sources to ApkTrack, there are two ways to go as of now.

1) Editing [this file](https://github.com/JusticeRage/ApkTrack/blob/master/assets/sources.json) and submitting a pull request.
2) Telling me about a repository and I will edit the aforementioned file myself.

I will look into GuardianProject, but for now, I keep being redirected to [this page](https://guardianproject.info/fdroid/repo/?fingerprint=B7C2EEFD8DAC7806AF67DFCD92EB18126BC08312A7F2D6F3862E46013C7A6135) and can't access any app information.

**Comment by Mosrite** [comment]
I'm really not an expert. I added "https://guardianproject.info/repo/" as additional repository on F-Droid and it works fine. I have no idea how F-Droid handles the repository.
Another interesting repository might be the one of I2P: https://f-droid.i2p.io/repo

**Comment by JusticeRage** [comment]
The latest [beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk) includes Guardian Project and I2P as available update sources!
Let me know if this fixes the issue for you!
