### ISSUE TITLE
ApkTrack keeps old version even after updating app

### ISSUE THREAD

**Issue by precla** [JusticeRage/ApkTrack#31]
I encountered a bug. For example:
I have Telegram installed (v 2.6.0) and made today a check with ApkTrack. It showed me that 2.6.1 is available so i got the new version and installed it. Going back to ApkTrack, and even after a refresh it still shows that 2.6.0 is installed on my device.
The only way to 'fix' this is by going into Android Settings and clear data of ApkTrack.

**Comment by JusticeRage** [comment]
Thank you for reporting this. The latest Beta APK contains a feature to automatically detect app updates, installs and uninstalls. It may not work perfectly yet, and logcats of test sessions are very welcome.
In the meantime, for the stable release, the better way to 'fix' this is by using the "Detect updated apps" button:

![Detect updated apps](http://img11.hostingpics.net/pics/164343updateapps.png)

**Comment by precla** [comment]
Thanks! Haven't tried that one.. my fault

**Comment by JusticeRage** [comment]
No problem! As I said, the process should become automatic in any case!
