### ISSUE TITLE
Consolidate update notifications

### ISSUE THREAD

**Issue by phipolis** [JusticeRage/ApkTrack#32]
ApkTrack creates a separate notification for each update it finds, if there are many it floods my notification area and lock screen. I propose using a single notification, similar to Play Store. "Updates available: Chrome, Firefox, and 3 others", adding to the list as more are found. Tapping the notification brings up the list of all updates.
Thanks for this project!

**Comment by phipolis** [comment]
One other thing about the notifications: tapping them doesn't dismiss and bring up the ApkTrack activity, it just stays there.

**Comment by JusticeRage** [comment]
Good idea!
I'll work on this when I get some free time!

**Comment by phipolis** [comment]
&hearts;!

**Comment by JusticeRage** [comment]
Hi! I've found time to work on this, and I have posted a [prototype](http://kwiatkowski.fr/apktrack/ApkTrack_phipolis.apk).
Let me know if you think this solves the issue!

**Comment by phipolis** [comment]
I love it! It's everything I dreamed of!
