### ISSUE TITLE
Ignore frozen apks

### ISSUE THREAD

**Issue by phipolis** [JusticeRage/ApkTrack#33]
It would be really nice if ApkTrack was aware of disabled/frozen packages and didn't check for updates to them. Play Store ignores disabled apps, F-Droid doesn't but that [hopefully](https://gitlab.com/fdroid/fdroidclient/issues/23) will change.

(packages are disabled by the adb shell command "pm disable com.package.name", identical to what Titanium Backup calls "Freeze")

**Comment by JusticeRage** [comment]
I have no idea how to do this yet, but I'll look into it at a later date.
There are however some more important things I want to do first!

**Comment by JusticeRage** [comment]
Fixed in version 2.0 (93e4e93bd1c48cb6ec1db40efc144eaafbf61276).
This is only done during ApkTrack's app discovery (during the first launch) however.
