### ISSUE TITLE
Preferred search engine setting does not display change immediately 

### ISSUE THREAD

**Issue by landry314** [JusticeRage/ApkTrack#34]
When you change the preferred search engine in settings, it does not immediately display the change until you back out of settings and come back in...

**Comment by JusticeRage** [comment]
That's weird. I've just tried it a minute ago and it performs as expected. Which device are you using? 
Could you submit a logcat so I can try to see what is going on?

**Comment by landry314** [comment]
same behavior on both the ASUS Transformer Infinity and Samsung Galaxy Relay running CM 10.2.1.

this might be related to having a firewall up but both firefox and apktrack are allowed through.

**Comment by tetsuo55** [comment]
I cannot confirm this issue. 

I tried on SDK 16 and SDK 23 emulators and it worked as expected
