### ISSUE TITLE
(no update information found) on 1.0c

### ISSUE THREAD

**Issue by landry314** [JusticeRage/ApkTrack#35]
With every search engine and every APK, I get no information...

Is APKTrack fetching data in some roundabout way that is hitting my firewall?

**Comment by JusticeRage** [comment]
APKTrack indeed performs some web requests. If you have a firewall installed (maybe XPrivacy restricting Internet access?), then ApkTrack will not be able to retrieve update information.

I will need a logcat in order to pinpoint the precise error which is occurring.

**Comment by landry314** [comment]
I have the same failed behavior on both the ASUS Transformer Infinity and Samsung Galaxy Relay running CM 10.2.1 and Android Firewall 2.3.5 which are allowing traffic out to both Firefox and APKTrack but blacklisting mostly everything else.

Does APKTrack require some system resource to be allowed through as well?

**Comment by JusticeRage** [comment]
I don't believe so.
Could you please post an error log of the application while performing an update check? I really need this to investigate. Here is a [tutorial](http://forum.xda-developers.com/android/help/guide-easiest-to-utilize-catlog-t2865994) in case you need it.

**Comment by landry314** [comment]
04-03 20:56:34.988 I/ActivityManager(486): Killing 3744:fr.kwiatkowski.ApkTrack/u0a10083: remove task
04-03 20:56:35.008 I/WindowState(486): WIN DEATH: Window{41d155d8 u0 fr.kwiatkowski.ApkTrack/fr.kwiatkowski.ApkTrack.MainActivity}
04-03 20:56:40.008 I/ActivityManager(486): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=fr.kwiatkowski.ApkTrack/.MainActivity bnds=[778,620][922,764]} from pid 740
04-03 20:56:40.078 I/ActivityManager(486): Start proc fr.kwiatkowski.ApkTrack for activity fr.kwiatkowski.ApkTrack/.MainActivity: pid=5873 uid=10083 gids={50083, 3003, 1028}
04-03 21:05:54.338 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.jtschohl.androidfirewall
04-03 21:05:54.348 V/ApkTrack(5873): Play Store check returned: NETWORK_ERROR
04-03 21:05:54.368 V/ApkTrack(5873): MainActivity received NETWORK_ERROR for Android Firewall.
04-03 21:05:56.348 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.rovio.angrybirds
04-03 21:05:56.358 V/ApkTrack(5873): Play Store check returned: NETWORK_ERROR
04-03 21:05:56.368 V/ApkTrack(5873): MainActivity received NETWORK_ERROR for Angry Birds.
04-03 21:08:11.498 V/ApkTrack(5873): Aborting automatic checks due to user preferences.
04-03 21:13:25.748 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.jtschohl.androidfirewall
04-03 21:13:26.238 V/ApkTrack(5873): Play Store check returned: ERROR
04-03 21:13:26.238 V/ApkTrack(5873): Trying AppBrain...
04-03 21:13:26.238 V/ApkTrack(5873): Requesting https://www.appbrain.com/app/google/com.jtschohl.androidfirewall
04-03 21:13:26.448 V/ApkTrack(5873): Nothing matched by the regular expression.
04-03 21:13:26.448 D/ApkTrack(5873): <html>
04-03 21:13:26.448 D/ApkTrack(5873): <head>
04-03 21:13:26.448 D/ApkTrack(5873): <script src='https://www.google.com/recaptcha/api.js'></script>
04-03 21:13:26.448 D/ApkTrack(5873): <title>AppBrain</title>
04-03 21:13:26.448 D/ApkTrack(5873): </head>
04-03 21:13:26.448 D/ApkTrack(5873): <body>
04-03 21:13:26.448 D/ApkTrack(5873): <h3>You have reached AppBrain</h3>
04-03 21:13:26.448 D/ApkTrack(5873): <form action="/humancheck" method="POST">
04-03 21:13:26.448 D/ApkTrack(5873): <div class="g-recaptcha" data-sitekey="6LcUtgITAAAAAFM_FAYUbQ7C3It9lKbYv_TBbt6M"></div>
04-03 21:13:26.448 D/ApkTrack(5873): <input type='hidden' name='next' value="" id='location'>
04-03 21:13:26.448 D/ApkTrack(5873): <p>
04-03 21:13:26.448 D/ApkTrack(5873): <input type='submit' value="Please click here to continue">
04-03 21:13:26.448 D/ApkTrack(5873): </p>
04-03 21:13:26.448 D/ApkTrack(5873): </form>
04-03 21:13:26.448 D/ApkTrack(5873): <script>
04-03 21:13:26.448 D/ApkTrack(5873): document.getElementById('location').value = window.location.href;
04-03 21:13:26.448 D/ApkTrack(5873): </script>
04-03 21:13:26.448 D/ApkTrack(5873): </body>
04-03 21:13:26.448 D/ApkTrack(5873): </html>
04-03 21:13:26.448 V/ApkTrack(5873): Requested page: APPBRAIN
04-03 21:13:26.498 V/ApkTrack(5873): AppBrain check returned: SUCCESS
04-03 21:13:26.508 V/ApkTrack(5873): MainActivity received SUCCESS for Android Firewall.
04-03 21:13:28.508 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.rovio.angrybirds
04-03 21:13:28.728 V/ApkTrack(5873): Play Store check returned: ERROR
04-03 21:13:28.728 V/ApkTrack(5873): Trying AppBrain...
04-03 21:13:28.728 V/ApkTrack(5873): Requesting https://www.appbrain.com/app/google/com.rovio.angrybirds
04-03 21:13:28.908 V/ApkTrack(5873): Nothing matched by the regular expression.
04-03 21:13:28.908 D/ApkTrack(5873): <html>
04-03 21:13:28.908 D/ApkTrack(5873): <head>
04-03 21:13:28.908 D/ApkTrack(5873): <script src='https://www.google.com/recaptcha/api.js'></script>
04-03 21:13:28.908 D/ApkTrack(5873): <title>AppBrain</title>
04-03 21:13:28.908 D/ApkTrack(5873): </head>
04-03 21:13:28.908 D/ApkTrack(5873): <body>
04-03 21:13:28.908 D/ApkTrack(5873): <h3>You have reached AppBrain</h3>
04-03 21:13:28.908 D/ApkTrack(5873): <form action="/humancheck" method="POST">
04-03 21:13:28.908 D/ApkTrack(5873): <div class="g-recaptcha" data-sitekey="6LcUtgITAAAAAFM_FAYUbQ7C3It9lKbYv_TBbt6M"></div>
04-03 21:13:28.908 D/ApkTrack(5873): <input type='hidden' name='next' value="" id='location'>
04-03 21:13:28.908 D/ApkTrack(5873): <p>
04-03 21:13:28.908 D/ApkTrack(5873): <input type='submit' value="Please click here to continue">
04-03 21:13:28.908 D/ApkTrack(5873): </p>
04-03 21:13:28.908 D/ApkTrack(5873): </form>
04-03 21:13:28.908 D/ApkTrack(5873): <script>
04-03 21:13:28.908 D/ApkTrack(5873): document.getElementById('location').value = window.location.href;
04-03 21:13:28.908 D/ApkTrack(5873): </script>
04-03 21:13:28.908 D/ApkTrack(5873): </body>
04-03 21:13:28.908 D/ApkTrack(5873): </html>
04-03 21:13:28.908 V/ApkTrack(5873): Requested page: APPBRAIN
04-03 21:13:28.968 V/ApkTrack(5873): AppBrain check returned: SUCCESS
04-03 21:13:28.988 V/ApkTrack(5873): MainActivity received SUCCESS for Angry Birds.
04-03 21:14:15.288 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.jtschohl.androidfirewall
04-03 21:14:15.488 V/ApkTrack(5873): Play Store check returned: ERROR
04-03 21:14:15.488 V/ApkTrack(5873): Trying AppBrain...
04-03 21:14:15.488 V/ApkTrack(5873): Requesting https://www.appbrain.com/app/google/com.jtschohl.androidfirewall
04-03 21:14:15.658 V/ApkTrack(5873): Nothing matched by the regular expression.
04-03 21:14:15.658 D/ApkTrack(5873): <html>
04-03 21:14:15.658 D/ApkTrack(5873): <head>
04-03 21:14:15.658 D/ApkTrack(5873): <script src='https://www.google.com/recaptcha/api.js'></script>
04-03 21:14:15.658 D/ApkTrack(5873): <title>AppBrain</title>
04-03 21:14:15.658 D/ApkTrack(5873): </head>
04-03 21:14:15.658 D/ApkTrack(5873): <body>
04-03 21:14:15.658 D/ApkTrack(5873): <h3>You have reached AppBrain</h3>
04-03 21:14:15.658 D/ApkTrack(5873): <form action="/humancheck" method="POST">
04-03 21:14:15.658 D/ApkTrack(5873): <div class="g-recaptcha" data-sitekey="6LcUtgITAAAAAFM_FAYUbQ7C3It9lKbYv_TBbt6M"></div>
04-03 21:14:15.658 D/ApkTrack(5873): <input type='hidden' name='next' value="" id='location'>
04-03 21:14:15.658 D/ApkTrack(5873): <p>
04-03 21:14:15.658 D/ApkTrack(5873): <input type='submit' value="Please click here to continue">
04-03 21:14:15.658 D/ApkTrack(5873): </p>
04-03 21:14:15.658 D/ApkTrack(5873): </form>
04-03 21:14:15.658 D/ApkTrack(5873): <script>
04-03 21:14:15.658 D/ApkTrack(5873): document.getElementById('location').value = window.location.href;
04-03 21:14:15.658 D/ApkTrack(5873): </script>
04-03 21:14:15.658 D/ApkTrack(5873): </body>
04-03 21:14:15.658 D/ApkTrack(5873): </html>
04-03 21:14:15.658 V/ApkTrack(5873): Requested page: APPBRAIN
04-03 21:14:15.708 V/ApkTrack(5873): AppBrain check returned: SUCCESS
04-03 21:14:15.718 V/ApkTrack(5873): MainActivity received SUCCESS for Android Firewall.
04-03 21:14:17.768 V/ApkTrack(5873): Requesting https://play.google.com/store/apps/details?id=com.rovio.angrybirds
04-03 21:14:18.068 V/ApkTrack(5873): Play Store check returned: ERROR
04-03 21:14:18.068 V/ApkTrack(5873): Trying AppBrain...
04-03 21:14:18.068 V/ApkTrack(5873): Requesting https://www.appbrain.com/app/google/com.rovio.angrybirds
04-03 21:14:18.318 V/ApkTrack(5873): Nothing matched by the regular expression.
04-03 21:14:18.328 D/ApkTrack(5873): <html>
04-03 21:14:18.328 D/ApkTrack(5873): <head>
04-03 21:14:18.328 D/ApkTrack(5873): <script src='https://www.google.com/recaptcha/api.js'></script>
04-03 21:14:18.328 D/ApkTrack(5873): <title>AppBrain</title>
04-03 21:14:18.328 D/ApkTrack(5873): </head>
04-03 21:14:18.328 D/ApkTrack(5873): <body>
04-03 21:14:18.328 D/ApkTrack(5873): <h3>You have reached AppBrain</h3>
04-03 21:14:18.328 D/ApkTrack(5873): <form action="/humancheck" method="POST">
04-03 21:14:18.328 D/ApkTrack(5873): <div class="g-recaptcha" data-sitekey="6LcUtgITAAAAAFM_FAYUbQ7C3It9lKbYv_TBbt6M"></div>
04-03 21:14:18.328 D/ApkTrack(5873): <input type='hidden' name='next' value="" id='location'>
04-03 21:14:18.328 D/ApkTrack(5873): <p>
04-03 21:14:18.328 D/ApkTrack(5873): <input type='submit' value="Please click here to continue">
04-03 21:14:18.328 D/ApkTrack(5873): </p>
04-03 21:14:18.328 D/ApkTrack(5873): </form>
04-03 21:14:18.328 D/ApkTrack(5873): <script>
04-03 21:14:18.328 D/ApkTrack(5873): document.getElementById('location').value = window.location.href;
04-03 21:14:18.328 D/ApkTrack(5873): </script>
04-03 21:14:18.328 D/ApkTrack(5873): </body>
04-03 21:14:18.328 D/ApkTrack(5873): </html>
04-03 21:14:18.328 V/ApkTrack(5873): Requested page: APPBRAIN
04-03 21:14:18.378 V/ApkTrack(5873): AppBrain check returned: SUCCESS
04-03 21:14:18.378 V/ApkTrack(5873): NotificationReciever received SUCCESS for Angry Birds.

**Comment by landry314** [comment]
maybe it is better if i email you the file? how do i post this txt file so the HTML doesnt parse on github?
i tried wrapping everything in each of these tags: pre, xmp, code, textarea. none of them stopped github from parsing the html in my comment. frustrating.

**Comment by landry314** [comment]
by the way, i disabled the firewall to test and the same problem occurs. it is not the firewall.

**Comment by JusticeRage** [comment]
Then, it is probably because there really is no update information available for a given app... Which one is it?

**Comment by landry314** [comment]
it WAS all of them but the new version 1.1b is working for me on both my tablet and phone! i posted that log from 1.0c on my tablet. i should have tried 1.1b instead.

this seems to be closed!

**Comment by JusticeRage** [comment]
I'm glad to hear that!
