### ISSUE TITLE
Version 1.1a crashes on startup

### ISSUE THREAD

**Issue by landry314** [JusticeRage/ApkTrack#36]
Version 1.1a just crashes on startup every time on my Galaxy Relay with CM 10.2.1...

**Comment by JusticeRage** [comment]
That's a problem. I have a pending bug report that I need to look into and it could be the cause of this crash as well. In any case, a logcat will allow me to see exactly what is going wrong (here is a [tutorial](http://forum.xda-developers.com/android/help/guide-easiest-to-utilize-catlog-t2865994) in case you are not familiar with it).

EDIT : A new beta APK has been posted, let me know if it fixes the problem!

**Comment by landry314** [comment]
FIXED!! version 1.1b loads at startup without a crash!
