### ISSUE TITLE
possibility to search and filter within the applist

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#38]
I have nearly 300 apps installed and it is terrible to find a specific app or all apps within an specific updatestate.
It would be great, if it would be possible to search apps by Displayname and FQDN within the applist.
Also you should be able to only show apps that are not the current version, which should be the default to show on opening the app via notifition.

**Comment by JusticeRage** [comment]
A search feature is a nice idea. I'll work on it in the future!
I also agree that a filter for outdated apps would be useful and that it should be used by default when coming from the notification.

Good points!
