### ISSUE TITLE
Wrong version returned with the AppBrain update source. 

### ISSUE THREAD

**Issue by KibaNoOu** [JusticeRage/ApkTrack#40]
In the latest version of the apk (1.1d) if i try to search update for system application it shows me (Current: 1000000) instead of the current version.
![screenshot_2015-04-17-09-31-11](https://cloud.githubusercontent.com/assets/11923117/7197897/c5b99be2-e4e6-11e4-856b-172c29b64672.png)

**Comment by JusticeRage** [comment]
Hi! Thanks for reporting this! 
The "10000000" version number appears when AppBrain successfully prevents ApkTrack from scraping their website. The 1.1d update was released precisely to add more countermeasures : using 1.1d as well, I can successfully retrieve version information (I just tried it). Could you please post a logcat so I can investigate? 

I would also be interested in a capture of the logcat while clicking on "Android Wallpaper", because it shouldn't be marked as "null" :)

**Comment by KibaNoOu** [comment]
I've take a logcat using CatLog after click to the Chrome Null entry, here's a link to the .txt

https://drive.google.com/file/d/0B1LIIQezQMFMLURibGhZek9HMzQ/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/11923117/7204825/61246d6c-e525-11e4-824d-ea95dbafaa3c.png)

**Comment by JusticeRage** [comment]
Thanks a lot for the logcat!
It seems that where Play Store used to write "Varies with device" for certain apps, there is now nothing. I'll work on a fix soon!

**Comment by DJaeger** [comment]
I do not get any version numbers anymore for apps that vary on device in the Play Store.
So for none of my apps is AppBrain Proxy or AppBrain determined.

```
08-24 09:11:11.123 I/Timeline(25489): Timeline: Activity_windows_visible id: ActivityRecord{423d5c20 u0 fr.kwiatkowski.ApkTrack/.MainActivity t906} time:639867502
08-24 09:11:13.395 V/ApkTrack( 5159): No specified update source. Defaulting to: Play Store
08-24 09:11:13.395 V/ApkTrack( 5159): Requesting https://play.google.com/store/apps/details?id=org.mozilla.firefox_beta
08-24 09:11:13.735 V/ApkTrack( 5159): Version obtained: Variiert je nach Gerät
08-24 09:11:13.735 V/ApkTrack( 5159): This is not recognized as a version number.
08-24 09:11:13.735 V/ApkTrack( 5159): Play Store check returned: ERROR
08-24 09:11:13.735 V/ApkTrack( 5159): Requesting http://apktrack.kwiatkowski.fr/version/org.mozilla.firefox_beta
08-24 09:11:13.765 I/adblock.(17874): false: http://apktrack.kwiatkowski.fr/version/org.mozilla.firefox_beta (null)
08-24 09:11:14.396 V/ApkTrack( 5159): AppBrain Proxy check returned: ERROR
08-24 09:11:14.406 V/ApkTrack( 5159): Requesting https://f-droid.org/repository/browse/?fdid=org.mozilla.firefox_beta
08-24 09:11:14.876 V/ApkTrack( 5159): F-Droid check returned: ERROR
08-24 09:11:14.876 V/ApkTrack( 5159): Requesting http://repo.xposed.info/module/org.mozilla.firefox_beta
08-24 09:11:15.397 V/ApkTrack( 5159): Xposed Stable check returned: ERROR
08-24 09:11:15.397 V/ApkTrack( 5159): Requesting http://repo.xposed.info/module/org.mozilla.firefox_beta
08-24 09:11:15.857 V/ApkTrack( 5159): Xposed Beta check returned: ERROR
08-24 09:11:15.857 V/ApkTrack( 5159): Requesting http://www.appbrain.com/NOT-APP/org.mozilla.firefox_beta
08-24 09:11:16.388 V/ApkTrack( 5159): AppBrain check returned: ERROR
08-24 09:11:16.398 V/ApkTrack( 5159): MainActivity received ERROR for Firefox Beta.
```

**Comment by JusticeRage** [comment]
Thanks a lot for the heads up. The situation has been sorted I think: all the details have been posted here on [XDA](http://forum.xda-developers.com/showpost.php?p=62482849&postcount=146). Let's wait for a few days to see if any bugs persist, then I hope to close this issue once and for all :)
