### ISSUE TITLE
WhatsApp returns 'null' as latest version

### ISSUE THREAD

**Issue by precla** [JusticeRage/ApkTrack#44]
Since i get (null) for the latest WhatsApp version, i thought about this:
How about getting the info about latest version from:
https://www.whatsapp.com/android/
It's just a paragraph with class name 'version':

<p class="version">Version 2.12.44</p>

**Comment by JusticeRage** [comment]
The "null" issue is discussed in #40 and will be fixed soon.

Adding an app's official repository is always welcome though! This will be added to the next version!

**Comment by precla** [comment]
ok, thanks for info!
