### ISSUE TITLE
Update searches stop after background

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#46]
If the app was in background while it searchs for updates and comes back to foreground the applist refresh/reload (I think this is the cause) stops the update searches.

**Comment by JusticeRage** [comment]
Actually, the checks aren't cancelled. The spinner does disappear however, because the "is currently checking" information is lost during the refresh.
I've been meaning to correct this for a while.

**Comment by JusticeRage** [comment]
Fixed in version 2.0 (93e4e93bd1c48cb6ec1db40efc144eaafbf61276).
