### ISSUE TITLE
Use only broadcast receiver to update applist

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#49]
If you use broadcasts you don't need an complete applist update anymore, which can make the app much more fast and performant.

You only have to request the complete list after very first start and after force stop, so you can also remove the button for refresh the applist.
This would make the app much more intuitive and easy to use.

You can check on appstart, if the app was force stopped, this way:
http://stackoverflow.com/a/16014057

**Comment by JusticeRage** [comment]
I'm not completely convinced that this is the right way to handle it yet, but you're absolutely right that the way the applist is manipulated can be improved drastically. I'll add it to my ToDo list!

**Comment by DJaeger** [comment]
I don't mean to search for updates if an app was updated or do anything else.
Only to update the database, so that you don't have to refresh it on next start of the app.

**Comment by JusticeRage** [comment]
That's what I had understood. Moving the refresh of the database to the background would indeed reduce loadings.

**Comment by JusticeRage** [comment]
Fixed in version 2.0 (93e4e93bd1c48cb6ec1db40efc144eaafbf61276).
