### ISSUE TITLE
Add Amazon App-Store

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#51]
Add Amazon App-Store for searching updates.

**Comment by DJaeger** [comment]
I will add and pull if you are not faster.
Just a reminder to me.

**Comment by DJaeger** [comment]
Do we have an variable to vary on architecture and available api level or android os version?

**Comment by jvschiavo** [comment]
Any progress?

**Comment by JusticeRage** [comment]
Not really. I seem to remember that there were issues related to the store's language and region availability which made using it as an update source difficult.

**Comment by Olf0** [comment]
IMHO, the Amzon app store has become mostly irrelevant in 2016 / 2017 (almost no new apps are released there), so putting any *major* effort into this may not be worth it.

Furthermore this issue is duplicated in issue #55, which provides more technical details.

**Comment by JusticeRage** [comment]
Closing as it is indeed a duplicate!
