### ISSUE TITLE
Add Firefox Aurora and Nightly

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#52]
Add Firefox Aurora and Nightly

I will add and pull if you are not faster.
Just a reminder to me.

**Comment by JusticeRage** [comment]
I hadn't added those since those versions of Firefox have a built-in update mechanism. Feel free to add those sources, otherwise I'll do it when I get the chance!

**Comment by DJaeger** [comment]
I (and I think others too) dont use them regulary and it's not great if I want to test something with current aurora or current nightly and I have to update first, because it searches and downloads the update not until it is started, but than it is needed and should already be there.

**Comment by DJaeger** [comment]
Do we have an variable to vary on architecture and available api level or android os version?
There are versions for API 9-10 (2.3) and API 11(>3.0) for ARMv7 and x86.

**Comment by JusticeRage** [comment]
No, I had never encountered this case before.

**Comment by DJaeger** [comment]
As someone with Android lower that 4.2 can't use ApkTrack we can forgot about the API 9-10 Version.
But I'm not sure if he could use it with x86.
 90% of Android devices have ARM and most apps seem to have to be recompiled for x86 so I think we should assume an ARM device.
This is also the default option on Mozilla Aurora download site.
