### ISSUE TITLE
Merging demaged master

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#60]
At merging beta to master you have damaged some parts.
Have seen until now, that you removed the WhatsApp and Öffi sources.

Additionally, you have moved F-Droid in the build for me, but why not commited?
Now the most apps are again detected with the more current not FLOSS versions from Google Play.

**Comment by DJaeger** [comment]
You revert the sources order here:
https://github.com/JusticeRage/ApkTrack/commit/bcae6140b0c509196ff630edded8877e03b51aac

**Comment by JusticeRage** [comment]
Damn, there was a conflict during the merge and I seem to have overwritten the right sources file... :(
I'm not sure I understand your first message however. Is there something else than reverting to the previous version that should be done?

Do you mean I should go back to bcae614, or that the damage was done here?

**Comment by DJaeger** [comment]
The damage was done there.
All should be corrected with above linked PR
