### ISSUE TITLE
Version 1.1g: Also raise versionCode

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#66]
Hi,

f-droid is currently not able to detect and so automatically build the new 1.1g as you have not raised the versionCode from 9 to 10.

**Comment by JusticeRage** [comment]
Apologies for this.
I thought F-Droid relied on Git tags!

**Comment by ghost** [comment]
Hi,

no need to to apologize. :grinning: 

> I thought F-Droid relied on Git tags!

F-Droid relies on git tags for the auto update as well as on the version-code for the detection of an update itself.

If a new tag is pushed (like for 1.1g) the update mechanism is checking if the new tag contains a higher version-code and detects a new version based on the version code.

So for F-Droid to detect the new version 1.1g the tag also needs to moved to https://github.com/JusticeRage/ApkTrack/commit/28417560106e1566602f574a11db0c0af89e9e64

**Comment by JusticeRage** [comment]
The tag has been moved to this commit!
