### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#68]
Make a new release with all current changes (also the beta changes) so that Google Play and APKmirror search are working again.

**Comment by JusticeRage** [comment]
I've just finished working on a web proxy for AppBrain requests. Depending on whether they are willing to whitelist it (it caches all requests for 24h), I would like to include it in the next release. In any case, I'll make a stable release sometime next week!

**Comment by DJaeger** [comment]
Where do I find this proxy?
I would like to contribute to it, so that we can directly include my proposal in #65 into it.
Please make it public on GH or give me access to it.

**Comment by JusticeRage** [comment]
I haven't released it yet. If AppBrain decides that this proxy arrangement is no longer acceptable, I don't want to disclose my new anti-scraping techniques to them so soon.

I can give you a copy of the code over e-mail for now if you want.

It's written in Python/Flask by the way!

**Comment by DJaeger** [comment]
One of the less programming languages I don't worked with until now. :-D
Then I think I will start working for the webservice independantly in a language, I'm more proficient in.

BTW: Do you included AppBrain only as fallback for GPlay or does it include apps, that are not in GPlay?

**Comment by JusticeRage** [comment]
Sorry about that!
Let me know when you have made progress on your app. I will be able to
host it on my server.

AppBrain is not just a fallback. They provide actual version numbers
wherever Google Play returns messages like "Varies with the device". A
lot of information is missing without this source.

**Comment by DJaeger** [comment]
I'm also able to host it on my server and I have already registered the domain apktrack.org for this. ;-)

But as I proposed this Webservice should be possible to also give the correct versions for apps from GPlay, which versions differ by device.
This would be better as give back a version number, that could be wrong for this device.
This should be done by ask the API for the app's version with applied Android version.
Is then AppBrain still be needed?
Which "lot of information" would then also be lost?

**Comment by JusticeRage** [comment]
Oh, that's great then!
If your webapp can obtain versions for any devices, then AppBrain isn't
needed anymore. I can't wait to see your web service!

By "a lot of information", I just meant "versions for apps that GPlay
doesn't provide". Right out, without AppBrain, ApkTrack cannot find any
information for numerous apps.

**Comment by DJaeger** [comment]
Ok.
What do you think about a gh-page to be accessible at this domain?

**Comment by JusticeRage** [comment]
I'm okay with it. At some point, I'll probably write a quick page
explaining how to use the app. It's grown more complex since the first
time it was presented.

**Comment by DJaeger** [comment]
See #70 for GH-page

**Comment by JusticeRage** [comment]
I have released the 1.1h version just now.
The `sources.json` have been moved around again:
- AppBrain Proxy goes all the way to the top since it is supposed to be the the most stable and comprehensive source now
- F-Droid goes down a bit because of the old problem of package name collisions (Google Play Services get masked by another app).
- AppBrain goes all the way down, for the users who are adamant about querying them directly. Unless the proxy gets banned by AppBrain, I intend to remove this source.

**Comment by DJaeger** [comment]
We already have discussed this before...
F-Droid should be placed before GPlay and AppBrain, because we want to prefer the full open source versions.
With F-Droid down of them all users have very much false messages for new updates.
The message of only the GPlay service is much better than that.

In addition you should let the direct AppBrain source remain as fallback, as not everyone will get an update imediately if the proxy gets blocked.

**Comment by JusticeRage** [comment]
I know we have, but I do not agree with this.
I really would put F-Droid further up the list, but returning a wrong version for Google Play Services (i.e. a wrong version number for an app which is virtually on all devices) is not acceptable for me. I'm not sure the other way around is true: are there cases where the version available on Google Play is different than the one on F-Droid? In those cases, is the version from F-Droid more recent than the one on GPlay? I don't think we should prefer apps available on open source repositories. I think we should prefer the _latest_ apps.

**Comment by DJaeger** [comment]
As said last time:
The purpose of this app is to get informed for updates in different appstores, mainly GPlay.
Because of that we can assume, that nearly all users of this app will not have the GPlay Store and most also do not have GPlay services.

In addition much apps have a newer version in GPlay Store than on F-Droid, as the upstream goes proprietary.
Also the GPlay services are newer on AppBrain (it is not available on GPlay Store) as on F-Droid, but as I stated before there should be more users of this app with the μg Project version as with the Google version.

This all are reasons for the move to the top of F-Droid we discussed before.
And since that change the app has much lesser wrong update informations.

**Comment by DJaeger** [comment]
And users of this app mostly hate Google and because of that use alternatives.
The most common alternative AppStore for "Google Haters" is F-Droid.

**Comment by JusticeRage** [comment]
> In addition much apps have a newer version in GPlay Store than on F-Droid, as the upstream goes proprietary.

If the upstream goes proprietary, that means that the former, open source version is no longer supported, is now outdated and should either be upgraded or uninstalled.

> there should be more users of this app with the μg Project version as with the Google version.

I think this is conjecture. The µg Project is not a complete replacement for the Play Services, and some apps (like TextSecure and I think Whatsapp) rely on Google's Push Infrastructure. So I don't think this is as simple as "no Play Store implies no Play Services".

In any case, if this AppBrain Proxy things holds up, the Play Store update source can probably be removed - AppBrain (direct or not) almost always has the same info anyway.

**Comment by DJaeger** [comment]
> If the upstream goes proprietary, that means that the former, open source version is no longer supported, is now outdated and should either be upgraded or uninstalled.

No.
Often there are simply new features included, which the developer do not want to offer as source code.

> I think this is conjecture. The µg Project is not a complete replacement for the Play Services

For what do you need the Play Services other than for the GPlay Store?

> and some apps (like TextSecure and I think Whatsapp) rely on Google's Push Infrastructure.

But not there alternatives that are also available in F-Droid, like SMSSecure and Telegram.

> So I don't think this is as simple as "no Play Store implies no Play Services".

Like I said before, for what do you need Play Services other than for the Play Store?

> In any case, if this AppBrain Proxy things holds up, the Play Store update source can probably be removed - AppBrain (direct or not) almost always has the same info anyway.

That's also not completely correct.
As AppBrain always tells the newest version, if compatible or not, for all apps incl. the system apps.

**Comment by JusticeRage** [comment]
> As AppBrain always tells the newest version, if compatible or not, for all apps incl. the system apps.

The Play Store may return either the latest version (if the version is the same for all devices) or "Varies with device).

Look, I really don't have the energy to fight over this issue. Arrange the `sources.json` the way you want, as long as the AppBrain Proxy remains on top, and I'll merge it and not touch it again.

**Comment by DJaeger** [comment]
For more about the sources selection see #41.
