### ISSUE TITLE
GH-page

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#70]
A GH-Page should be created, that presents the app and it's features.

**Comment by DJaeger** [comment]
@SecUpwN: Would you help on this?

**Comment by JusticeRage** [comment]
I would!

**Comment by DJaeger** [comment]
Also great. ;-)
I find the GH-Page of [Android-IMSI-Catcher-Detector](https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/) by @SecUpwN so great so I asked him.
And he seems to be also a user of this app, as he already filed an issue.

**Comment by SecUpwN** [comment]
Thanks for mentioning me and also for loving our website, @DJaeger. As the project mentainer of [AIMSICD](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) I enjoy using [GitHub Pages](https://pages.github.com/), which enables the project owner (in this case @JusticeRage) to automatically generate a neat look website from the aready existing `README` without any further hassles. The only thing that you need to ensure, is that your `README` on GitHub looks the way it should. Give it it a shot and share the link, please! Of course I'll be around should any questions arrive in he process.

**Comment by DJaeger** [comment]
Which link do you mean, @SecUpwN?

**Comment by SecUpwN** [comment]
@DJaeger, I mean the link to the website of this project, once @JusticeRage created it. ;-)

**Comment by DJaeger** [comment]
@JusticeRage: The dommain is configured to use GH-Pages.
Would you please create it?
A can find a HowTo here:
https://pages.github.com/

@SecUpwN: It will be available on http://apktrack.org .
We will ping you if it is created.

**Comment by JusticeRage** [comment]
It's done!
The contents were generated from README.md for now, but I'll have to update it. Soon, hopefully.

**Comment by DJaeger** [comment]
Great.
Very basic, but it works. :-)
The first open source project I'm sponsoring. ;-)

**Comment by JusticeRage** [comment]
And the first one I'm working on!

**Comment by SecUpwN** [comment]
Glad to see you guys succeeding with this!

> The first open source project I'm sponsoring. ;-)

Ok, why won't you sponsor us as well, @DJaeger? ^^

**Comment by DJaeger** [comment]
> > The first open source project I'm sponsoring. ;-)
> 
> Ok, why won't you sponsor us as well, @DJaeger? ^^

How should I sponsor you?

**Comment by SecUpwN** [comment]
> How should I sponsor you?

With [Bountysource](https://www.bountysource.com/teams/android-imsi-catcher-detector/issues), for example.

**Comment by DJaeger** [comment]
In my understanding this is funding and not sponsoring.
For me sponsoring is giving away something to use, something "productive" and funding giving away money.
But let us talk about that by mail and not here.

**Comment by JusticeRage** [comment]
Hey @DJaeger!
Would it be possible for you to create a CNAME record redirecting `translate.apktrack.org` to `apktrack.oneskyapp.com`? I've registered with this service so translators can help translate the app into other languages!
Thanks!

**Comment by DJaeger** [comment]
@JusticeRage: Sorry for the late respond.
I have created a redirect, as a CNAME or a reverse proxy will result in a certificate error or an infinite loop due to the https enforcement of oneskyapp.

**Comment by JusticeRage** [comment]
That'll work :) Thanks a lot!

**Comment by Olf0** [comment]
Accomplished my first ("fork" / clone and pull request) as well, hopefully it's O.K. (content and handling): See PR 118.
Travis does seem to be not working though, generating a check failure.  I already noticed, that something seems to be wrong with this Travis instance when editing ApkTrack's README.md (which contains an embedded link to it).

May I also suggest to change the description line of this project (currently somewhat lengthy and convoluted) to:
ApkTrack is an Android app, which checks if updates for installed APKs are available. 

Cheers & HTH

P.S.: By reading through the messages in this issue, I came to the conclusion that all aspects of it are covered now, so IMO it can be closed (after handling my PR, of course ;) ).

**Comment by Olf0** [comment]
WRT the webpage ApkTrack.org: "[The contents were generated from README.md for now, but I'll have to update it.](https://github.com/JusticeRage/ApkTrack/issues/70#issuecomment-131387256)" is done by PR #128 .

So this issue can be closed, IMO.
