### ISSUE TITLE
Request: provide download links/sha256 of apk files

### ISSUE THREAD

**Issue by frief** [JusticeRage/ApkTrack#71]
the former would be nice to have an independent means of installation.  
the latter would be nice to allow for a consistency check.  

Thanks for ApkTrack!

**Comment by JusticeRage** [comment]
Duplicate of #65.
As for checksums, I'm not sure they are necessary. APKs have an embedded cryptographic signature and the OS will not upgrade packages if there is a mismatch with the currently installed one. (Installing new packages is a different issue, but one ApkTrack is not concerned with.)
