### ISSUE TITLE
Fall back to Play Store

### ISSUE THREAD

**Issue by DJaeger** [JusticeRage/ApkTrack#74]
The app is not falling back to Play Store if AppBrain is failing.
All the Apps, that are from Play Store either have AppBrain set as Update Source and a version detected or no Update Source and the message "Unable to read version information".
If I manually set the update source to AppBrain I get the same message.
If I manually set it to Play Store it is successfully retrieving a version number.

**Comment by DJaeger** [comment]
BTW:
Really great update.

**Comment by JusticeRage** [comment]
I'll look into this. Do you have an example of an app which shows this behaviour?

**Comment by DJaeger** [comment]
For example "CACert.org installer"

**Comment by JusticeRage** [comment]
Okay, I've been able to reproduce the bug. This is caused by an unexpected response returned by AppBrain (and in turn the proxy) when the app exists in their database but no version information is available - I'm guessing.
In any case, thanks for reporting this!
