### ISSUE TITLE
Support more devices

### ISSUE THREAD

**Issue by JusticeRage** [JusticeRage/ApkTrack#8]
ApkTrack has been compiled with a very conservative API level (who'd have thought it would one day run on another device than mine?). Currently, it won't install on Android < 4.4.

Lower the requested API level as much as possible to allow more people to use the application.

**Comment by JusticeRage** [comment]
API level lowered to 17 (Android >= 4.2).
I'll see if it can be improved further.

**Comment by IceLancerSR** [comment]
Hello. Well its not really wanting to be installed on my 4.2.1 Android  :-(

**Comment by JusticeRage** [comment]
Ah... The APK is supposed to be up to date. Could you please post a copy of the error message when you're trying to perform the installation?
Alternately, I have posted a [more recent APK](http://kwiatkowski.fr/apktrack/ApkTrack_BoBeR182.apk) for another user, while trying to fix some bugs. See if this one works!

**Comment by IceLancerSR** [comment]
In both apk's same thing
"there was a problem parsing the package"
Usually known as not supported by OS version.4.2.1 is mine.

**Comment by JusticeRage** [comment]
I'll look into it, thanks!

**Comment by JusticeRage** [comment]
Hey ! I posted a new [beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk). It turns out the minSdkVersion in my Manifest was wrong. I was sure I had reduced it to 17 earlier.
Please let me know if this fixes your issues!

**Comment by IceLancerSR** [comment]
Alright this one does install !
Although it does not seem to do any checking.
It keeps saying (last check : never) i tried google play search engine and default google same result

I tried over Wifi.Maybe there is some dependance missing still for older os?
Does it require google play to be signed in? Because it beats the purpose then ?

![screenshot_2015-03-02-10-35-52](https://cloud.githubusercontent.com/assets/4452102/6438382/4374ebce-c07d-11e4-9626-c0945967ad68.png)

**Comment by IceLancerSR** [comment]
Ok i tried cat log to debug error log
this is what i got:
play.google.com/store/apps/details?id=com.google.android.apps.uploader could not be retrieved (null)

**Comment by JusticeRage** [comment]
Thank you for helping me debug ApkTrack!
From what I understand, the second error seems to indicate a memory leak somewhere. As for the checking problem, there shouldn't be any dependencies missing, and a Play Store account is definitely not required. I'll investigate this if I manage to reproduce it.

Could you please post a full logcat dump, and not just an excerpt? I would need more information to look into this.

**Comment by IceLancerSR** [comment]
https://mega.co.nz/#!llgTiJQZ!2dJhgPQAutPtUcaFQ-2_fpJ6o7oH3W5QW79yEVftZ6k

here it is.

**Comment by JusticeRage** [comment]
I'll admit that I'm puzzled. There isn't much information to go on in the logs. The "null" exception message is particularly unhelpful. It won't solve the problem, but I have updated the [beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk) to include more logging. Could you please post a new logcat please? Hopefully, it'll give me more to investigate!

**Comment by IceLancerSR** [comment]
Here https://mega.co.nz/#!toJ2yKyA!iq-_N5trjIM1D8QgrTWRQPl2mRYKJYdPSHHAiuiI0RI
there are some java errors showing now

**Comment by JusticeRage** [comment]
Yay! Java errors.
I found the problem: for some reason, `WebSettings.getDefaultUserAgent` returned `null` on your device. The application now reverts to a Nexus 5 user agent in this case.
The [beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk) has been updated again and I'm pretty confident that this bug, at least, should be fixed.

**Comment by IceLancerSR** [comment]
![screenshot_2015-03-02-22-30-44](https://cloud.githubusercontent.com/assets/4452102/6451001/832bbf3c-c0e0-11e4-9285-e409482f8d7f.png)
Perfect Indeed it is working !
P.S My phone chips is mtk 6589 so if its working for me it should be working for many other mtk's

**Comment by IceLancerSR** [comment]
Now if i could just feed all this info to my PC to raccoon or apk leecher that would be awesome :P (for auto dl of updated apks..

**Comment by etam** [comment]
Is it possible to lower required version to 4.1.2? It's the currently supported version by Jolla devices.

**Comment by JusticeRage** [comment]
I'm still planning on lowering the required version indeed. I can't give you an estimated date though, I don't have as much time to work on ApkTrack as I used to...

**Comment by JusticeRage** [comment]
@etam I have posted a new [beta APK](http://kwiatkowski.fr/apktrack/ApkTrack_beta.apk) which lowers the required API level to 15 (Android 4.0.3).
Let me know if it works on your device!

**Comment by etam** [comment]
Unfortunately, when trying to install, After agreeing to permissions required I get "Application was not installed".

**Comment by JusticeRage** [comment]
Ah :( Is there anything in the logcat which would indicate why the installation failed?

**Comment by etam** [comment]
http://susepaste.org/81099989

**Comment by JusticeRage** [comment]
Thanks a lot. This looks like a problem with the app's cryptographic signature.
I did some research which pointed me to this [SO answer](https://stackoverflow.com/a/8037732/1422536). Basically, it says that there are problems when APKs are signed with JDK 1.7, which is weird because it feels like I've always been doing this... Or has Debian's Java version been updated recently without me noticing?

In any case, I have tried re-signing the APK with additional options which should solve the problem. Could you try downloading this new APK and letting me know if it works for you?

http://kwiatkowski.fr/apktrack/ApkTrack_etam.apk

**Comment by etam** [comment]
This one installs and works without any problems. Thanks :)

**Comment by JusticeRage** [comment]
Great! I'll make sure to sign future releases properly then. 
Let me know if you encounter any bugs!
