### ISSUE TITLE
Check on ApkTrack Stable stopped working

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#86]
Hi,

it seem the check for ApkTrack on "ApkTrack Stable" stopped working. This is because:

https://github.com/JusticeRage/ApkTrack/blob/2.1.0/src/main/assets/sources.json

leads to: https://apktrack.kwiatkowski.fr/apk/version.html which currently 404.

**Comment by JusticeRage** [comment]
Thanks for letting me know!
This page was deleted by mistake yesterday while I deleted old APKs downloaded by the proxy. It should be back to normal now!

**Comment by ghost** [comment]
Hi,

thanks for fixing. Working again as expected.
