### ISSUE TITLE
Apk from Play Store?

### ISSUE THREAD

**Issue by ghost** [JusticeRage/ApkTrack#95]
Hi! The app is really amazing, but the download of the last apks from Play Store don't start/work.. is possible resolve this problem??

**Comment by JusticeRage** [comment]
Hi! Downloading apps from the Play Store is not implemented... Instead, a search link is provided for the device's browser (the magnifying glass icon).
Is there a browser installed on your device?

**Comment by ghost** [comment]
Yes, I use Lightning. However, as soon as I open the connection, Google tells me that the browser is no longer supported. 

If I open the corresponding page from PC tells me that serves the mobile version. 

Anyway, I noticed that there are apps / sites that allow you to download apks without use the Play Store .. wouldn't it be possible so implement this function in the your app?? The app become even more useful and necessary, in my opinion!

**Comment by DJaeger** [comment]
> Anyway, I noticed that there are apps / sites that allow you to download apks without use the Play Store ..
> wouldn't it be possible so implement this function in the your app?? The app become even more useful and necessary, in my opinion!

This is already implemented.
You have to choose "Evozi" or "APK Mirror" as search engine in the setting.

As Google is not supporting your browser you can also choose "DuckDuckGo" as search engine in the settings, which is supporting much more browsers.

**Comment by ghost** [comment]
I understand. Thank you!
