### ISSUE TITLE
Wrong version returned for com.palabs.artboard 

### ISSUE THREAD

**Issue by gerroon** [JusticeRage/ApkTrack#96]
Hi

It seems the updates are not reflected? I have an app called artboard, it is still showing 1.9 but according to appbrain it is upto 2.0.

**Comment by JusticeRage** [comment]
Hi,
If you look at the [AppBrain page](http://www.appbrain.com/app/artboard-creative-drawing/com.palabs.artboard), you'll notice that despite the dates, the version displayed at the top is the 1.9, so it's possible their API is erroneously returning it as the latest one.
Although I don't think this is the case here, ApkTrack also has a 24-hour cache for application versions, so if this new information was added very recently, it may take up to a day to be displayed.

In any case, I would tend to think that the issue isn't caused directly by ApkTrack but by its data source.

**Comment by gerroon** [comment]
thanks for the update. I thought I could report it in case there are issues with caching and such

**Comment by JusticeRage** [comment]
No problem. Thanks for notifying me!
